class ccl:
    AUTHORIZATION = "Authorization"


class lcl:
    id = "id"
    name = "name"
    code = "code"
    symbol = "symbol"
    testing = "testing"
    user_id = "user_id"
    default = "default"
    password = "password"
    timezone = "timezone"
    created_on = "created_on"
    production = "production"
    development = "development"
    created_via = "created_via"
    dc_profile_id = "dc_profile_id"
    num_of_debtors = "num_of_debtors"
    registered_via = "registered_via"
    total_payables = "total_payables"
    num_of_creditors = "num_of_creditors"
    primary_currency = "primary_currency"
    total_receivables = "total_receivables"
    primary_currency_d = "primary_currency_d"
    payables_and_receivables_d = "payables_and_receivables_d"


class ucl:
    WAT = "WAT"
    API = "API"
    TESTING = "TESTING"
    SECRET_KEY = "SECRET_KEY"
    PRODUCTION = "PRODUCTION"
    SOURCE_HASH = "SOURCE_HASH"
    COMMIT_HASH = "COMMIT_HASH"
    DEVELOPMENT = "DEVELOPMENT"
    TESTING_ENV = "TESTING_ENV"
    PRODUCTION_ENV = "PRODUCTION_ENV"
    DEVELOPMENT_ENV = "DEVELOPMENT_ENV"
    TP_DEV_PASSWORD = "TP_DEV_PASSWORD"
    TRADEPALLY_LOCALHOST_API_AUTH_TOKEN = "TRADEPALLY_LOCALHOST_API_AUTH_TOKEN"
    TRADEPALLY_PRODUCTION_API_AUTH_TOKEN = "TRADEPALLY_PRODUCTION_API_AUTH_TOKEN"
