class ccl:
    DEBTOR = "Debtor"
    CREDITOR = "Creditor"
    AUTHORIZATION = "Authorization"


class lcl:
    id = "id"
    pin = "pin"
    name = "name"
    code = "code"
    params = "params"
    symbol = "symbol"
    headers = "headers"
    testing = "testing"
    user_id = "user_id"
    default = "default"
    debtors = "debtors"
    password = "password"
    creating = "creating"
    timezone = "timezone"
    user_pin = "user_pin"
    creditors = "creditors"
    created_on = "created_on"
    production = "production"
    development = "development"
    total_debts = "total_debts"
    created_via = "created_via"
    all_debtors = "all_debtors"
    root_domain = "root_domain"
    user_password = "user_password"
    all_creditors = "all_creditors"
    dc_profile_id = "dc_profile_id"
    total_credits = "total_credits"
    total_payments = "total_payments"
    num_of_debtors = "num_of_debtors"
    registered_via = "registered_via"
    total_payables = "total_payables"
    num_of_creditors = "num_of_creditors"
    primary_currency = "primary_currency"
    total_receivables = "total_receivables"
    primary_currency_d = "primary_currency_d"
    num_of_transactions = "num_of_transactions"
    current_book_balance = "current_book_balance"
    debtor_dc_profile_id = "debtor_dc_profile_id"
    creditor_dc_profile_id = "creditor_dc_profile_id"
    payables_and_receivables_d = "payables_and_receivables_d"


class ucl:
    WAT = "WAT"
    API = "API"
    TESTING = "TESTING"
    TP_DEV_PIN = "TP_DEV_PIN"
    SECRET_KEY = "SECRET_KEY"
    PRODUCTION = "PRODUCTION"
    SOURCE_HASH = "SOURCE_HASH"
    COMMIT_HASH = "COMMIT_HASH"
    DEVELOPMENT = "DEVELOPMENT"
    TESTING_ENV = "TESTING_ENV"
    PRODUCTION_ENV = "PRODUCTION_ENV"
    DEVELOPMENT_ENV = "DEVELOPMENT_ENV"
    TP_DEV_PASSWORD = "TP_DEV_PASSWORD"
    TRADEPALLY_LOCALHOST_API_AUTH_TOKEN = "TRADEPALLY_LOCALHOST_API_AUTH_TOKEN"
    TRADEPALLY_PRODUCTION_API_AUTH_TOKEN = "TRADEPALLY_PRODUCTION_API_AUTH_TOKEN"
